#!/bin/bash

read -p "username:       " username
read -p "pubkey:         " pubkey
read -p "sudo [y/n]:     " truthy
read -p "password [y/n]: " password

mkdir -p /home/$username/.ssh
touch /home/$username/.ssh/authorized_keys
echo $pubkey >>/home/$username/.ssh/authorized_keys
useradd -d /home/$username $username

if $truthy; then
    usermod -aG sudo $username
    passwd $username
else
    if $password; then
        passwd $username
    fi
fi

chown -R $username:$username /home/$username/
chown root:root /home/$username
chmod 700 /home/$username/.ssh
chmod 644 /home/$username/.ssh/authorized_keys
